### ISSUE TITLE
RegexpJavanator is broken

### ISSUE THREAD

**Issue by markozajc** [kazakovs/Javinator#3]
As I can see, `MainGame.java` uses `RegexpJavanator.java` as `IJavanator`. But when I look at `RegexpJavanator:67`, I quickly realise that something's not right there (always returns empty array). Please fix that!

**Comment by kazakovs** [comment]
Can't remember why I used RegexpJavinator, but it was obviously not ready. Currently I don't use it instead of it, I'm using second implementation.
